spring:
  application:
    name: pure-awesomeness
  servlet:
    multipart:
      max-file-size: 2MB

server:
  servlet:
    context-path: /pure-awesomeness
  http2:
    enabled: true

graphql:
  servlet:
    actuator-metrics: true
    async-timeout: 10000
    max-query-depth: 5
    exception-handlers-enabled: false

  ####################################### DEV Configs START #######################################
  ##### Turn OFF in PRODUCTION #####
  playground:
    endpoint: /pure-awesomeness/graphql
    enabled: true
    tabs:
      - name: Bank
        headers:
          SomeHeader: Some value
        query: classpath:playground/bank.graphql
        variables: classpath:playground/variables/bank_account_variables.json
      - name: Movies
        query: classpath:playground/movies.graphql
  ############# Turn OFF in PRODUCTION #############
  voyager:
    enabled: true

  ####################################### DEV Configs END #######################################


API_KEY: e7ca0ae7a80530814607bea559a6c827


